### ISSUE TITLE
Customize Scaffolding Templates

### ISSUE THREAD

**Issue by bricelam** [bricelam/EntityFramework.VisualStudio#9]
A gesture to bootstrap customization by adding the default templates into your project. Of course, we'd need support for templates in the first place. 😁

**Comment by ErikEJ** [comment]
@bricelam Time to close this? 🎉

**Comment by ErikEJ** [comment]
Just added this to the EF Core Power Tools menu:

![image](https://user-images.githubusercontent.com/4169187/186415928-04353962-bfdf-4b2a-a092-277faf1c6d0b.png)
